apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
  annotations:
    cloud.google.com/load-balancer-type: "External"
    kubernetes.io/ingress.global-static-ip-name: "backend-staging-ip"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    app: {{ .Release.Name }}-backend
